### ISSUE TITLE
Problems when running the docker

### ISSUE THREAD

**Issue by michalisk13** [techge/kiscap2amqp#1]
Hi,

First of all very nice project.
I don't know why it did not receive the attention it deserves.

I have some problems when running your solution.

Here is what I get:
./capture_linux_wifi/kiscap2amqp_linux_wifi: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./capture_linux_wifi/kiscap2amqp_linux_wifi)

Any idea on what may cause the problem?

Thanks,
Mak

**Comment by michalisk13** [comment]
Trying to install glibc from sources. Will see if any more errors

**Comment by techge** [comment]
Hey, good you could find out what's wrong. Totally forgot to respond, although I've read you message.

I am glad to see that someone finds the tool useful. Haven't used it for a while myself :)

**Comment by michalisk13** [comment]
Hey,

Very nice projects indeed :)

I am trying to understand your eewids architecture and the tools you used there. I never came across influxdb and telegraf and they look very nice tools.

I want to make a similar architecture for an event based system, in which if a sequence of different events happen within a specified timeframe will trigger.

For instance, if an Association Response Message followed by a Deauthentication Message within a timeframe of 60 seconds to issue a warning.

Do you think influxdb+telegraf is ideal for such system?

Thanks,
Mak

**Comment by techge** [comment]
> I want to make a similar architecture for an event based system, in which if a sequence of different events happen within a specified timeframe will trigger.

Cool, I still think it is a good idea to do that, it is just a lot of stuff that needs to get packed together.

> Do you think influxdb+telegraf is ideal for such system?

I sure do think so! At least that was my intention back then, though I never found the time to fully use the potential...
